---
title: "Untitled"
output:
  html_document:
    df_print: paged
date: "2023-03-07"
---

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
url_in <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"
file_names <- c("time_series_covid19_confirmed_US.csv",
                "time_series_covid19_confirmed_global.csv",
                "time_series_covid19_deaths_US.csv",
                "time_series_covid19_deaths_global.csv",
                "time_series_covid19_recovered_global.csv")
urls <- str_c(url_in, file_names)
US_cases <- read_csv(urls[1])
global_cases <- read_csv(urls[2])
US_deaths <- read_csv(urls[3])
global_deaths <- read_csv(urls[4])
global_recovered <- read_csv(urls[5])
```

```{r}
global_deaths <- global_deaths %>% 
  pivot_longer(cols=-c('Province/State', 'Country/Region', Lat, Long), 
                                                names_to="date", values_to="deaths") %>% 
  select(-c(Lat, Long))

global_cases <- global_cases %>% 
  pivot_longer(cols=-c('Province/State', 'Country/Region', Lat, Long), 
               names_to="date", values_to="cases") %>% 
  select(-c(Lat, Long))

global <- global_cases %>% 
  full_join(global_deaths) %>% 
  rename(Country_Region='Country/Region', Province_State='Province/State') %>% 
  mutate(date=mdy(date))

global <- global %>% filter(cases > 0)

summary(global)
```

```{r}
US_cases <- US_cases %>% 
  pivot_longer(cols=-(UID:Combined_Key), names_to="date", values_to="cases") %>% 
  select(Admin2:cases) %>% 
  mutate(date=mdy(date)) %>% 
  select(-c(Lat, Long_))

US_deaths <- US_deaths %>% 
  pivot_longer(cols=-(UID:Combined_Key), names_to="date", values_to="deaths") %>% 
  select(Admin2:deaths) %>% 
  mutate(date=mdy(date)) %>% 
  select(-c(Lat, Long_))

US <- US_cases %>% full_join(US_deaths)

US <- US %>% filter(cases > 0)

uid_lookup_url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"

uid <- read_csv(uid_lookup_url) %>% select(-c(Lat, Long_, Combined_Key, code3, iso2, iso3, Admin2))

global <- global %>% 
  left_join(uid, by=c("Province_State", "Country_Region")) %>% 
  select(-c(UID, FIPS)) %>% 
  select(Province_State, Country_Region, date, cases, deaths, Population)

global
```

```{r}
US_by_state <- US %>% group_by(Province_State, Country_Region, date) %>%
  summarize(cases=sum(cases), deaths=sum(deaths)) %>%
              select(Province_State, Country_Region, date, cases, deaths) %>%
              ungroup()
```

```{r}
US_totals <- US_by_state %>%
  group_by(Country_Region, date) %>%
  summarize(cases=sum(cases), deaths=sum(deaths)) %>%
  select(Country_Region, date, cases, deaths) %>%
  ungroup()

```

```{r}
US_totals %>%
  filter(cases > 0) %>%
  ggplot(aes(x=date, y=cases)) +
  geom_line(aes(color="cases")) +
  geom_point(aes(color="cases")) +
  geom_line(aes(y=deaths, color="deaths")) +
  geom_point(aes(y=deaths, color="deaths")) +
  scale_y_log10() +
  theme(legend.position="bottom", axis.text.x = element_text(angle=90)) +
  labs(title="COVID 19 in US", y=NULL)
```

```{r}
state <- "New York"
US_by_state %>%
  filter(Province_State == state) %>%
  filter(cases > 0) %>%
  ggplot(aes(x=date, y=cases)) +
  geom_line(aes(color="cases")) +
  geom_point(aes(color="cases")) +
  geom_line(aes(y=deaths, color="deaths")) +
  geom_point(aes(y=deaths, color="deaths")) +
  scale_y_log10() +
  theme(legend.position="bottom", axis.text.x = element_text(angle=90)) +
  labs(title="COVID 19 in New York", y=NULL)
```

```{r}
US_by_state <- US_by_state %>%
  mutate(new_cases = cases - lag(cases), new_deaths = deaths - lag(deaths))

US_totals <- US_totals %>%
  mutate(new_cases = cases - lag(cases), new_deaths = deaths - lag(deaths))
```

```{r}
US_totals %>%
  ggplot(aes(x=date, y=new_cases)) +
  geom_line(aes(color="new_cases")) +
  geom_point(aes(color="new_cases")) +
  geom_line(aes(y=new_deaths, color="new_deaths")) +
  geom_point(aes(y=new_deaths, color="new_deaths")) +
  scale_y_log10() +
  theme(legend.position="bottom", axis.text.x = element_text(angle=90)) +
  labs(title="New COVID 19 in US", y=NULL)
```

```{r}
US_by_state %>%
  filter(Province_State == state) %>%
  ggplot(aes(x=date, y=new_cases)) +
  geom_line(aes(color="new_cases")) +
  geom_point(aes(color="new_cases")) +
  geom_line(aes(y=new_deaths, color="new_deaths")) +
  geom_point(aes(y=new_deaths, color="new_deaths")) +
  scale_y_log10() +
  theme(legend.position="bottom", axis.text.x = element_text(angle=90)) +
  labs(title="New COVID 19 in New York", y=NULL)
```

```{r}
global %>%
  filter(cases > 0) %>%
  ggplot(aes(x=date, y=cases)) +
  geom_line(aes(color="cases")) +
  geom_point(aes(color="cases")) +
  geom_line(aes(y=deaths, color="deaths")) +
  geom_point(aes(y=deaths, color="deaths")) +
  scale_y_log10() +
  theme(legend.position="bottom", axis.text.x = element_text(angle=90)) +
  labs(title="COVID 19 Worldwide", y=NULL)
```

```{r}
mod <- lm(cases ~ deaths, data=US_by_state)
summary(mod)
```

Bias: As someone who was really interested in observing how covid has progressed it can be easy to try and represent the data unfairly. However, I made sure there wasn't any bias to the best of my ability and showed the data for what it is, rather than what I want it to be.